# Generated by Django 5.1.4 on 2025-02-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
